package raw

type CompMap struct {
	ProfileCometAppSectionSelfFriendsActionRendererActionsRendererNormalizationGraphql FbtLogging               `json:"ProfileCometAppSectionSelfFriendsActionRenderer_actionsRenderer$normalization.graphql,omitempty"`
	ProfileCometAppSectionSelfFriendsActionRendererReact                               BladeRunnerClient        `json:"ProfileCometAppSectionSelfFriendsActionRenderer.react,omitempty"`
	QPLInspector                                                                       BladeRunnerStreamHandler `json:"QPLInspector,omitempty"`
	BladeRunnerClient                                                                  BladeRunnerClient        `json:"BladeRunnerClient,omitempty"`
	BladeRunnerStreamHandler                                                           BladeRunnerStreamHandler `json:"BladeRunnerStreamHandler,omitempty"`
	WebSession                                                                         BladeRunnerStreamHandler `json:"WebSession,omitempty"`
	ProfileCometAppSectionFriendsListPopupMenuReact                                    CometCompatModalReact    `json:"ProfileCometAppSectionFriendsListPopupMenu.react,omitempty"`
	FalcoBladeRunnerTransport                                                          BladeRunnerStreamHandler `json:"FalcoBladeRunnerTransport,omitempty"`
	Ods                                                                                CometCompatModalReact    `json:"ODS,omitempty"`
	ProfileCometAboutProfileFieldSectionsRendererStyleRendererNormalizationGraphql     FbtLogging               `json:"ProfileCometAboutProfileFieldSectionsRenderer_styleRenderer$normalization.graphql,omitempty"`
	ProfileCometAboutProfileFieldSectionsRendererReact                                 BladeRunnerClient        `json:"ProfileCometAboutProfileFieldSectionsRenderer.react,omitempty"`
	MqttSkywalkerManager                                                               CometCompatModalReact    `json:"MqttSkywalkerManager,omitempty"`
	CometHovercardQueryRendererReact                                                   BladeRunnerStreamHandler `json:"CometHovercardQueryRenderer.react,omitempty"`
	CometPrivacySelectorDialogReact                                                    CometCompatModalReact    `json:"CometPrivacySelectorDialog.react,omitempty"`
	CometPrivacySelectorPickerContainerReact                                           CometCompatModalReact    `json:"CometPrivacySelectorPickerContainer.react,omitempty"`
	CometPrivacySelectorPushViewReact                                                  CometCompatModalReact    `json:"CometPrivacySelectorPushView.react,omitempty"`
	ProfileCometUpsellProfileFieldRendererRendererNormalizationGraphql                 FbtLogging               `json:"ProfileCometUpsellProfileFieldRenderer_renderer$normalization.graphql,omitempty"`
	ProfileCometUpsellProfileFieldRendererReact                                        BladeRunnerClient        `json:"ProfileCometUpsellProfileFieldRenderer.react,omitempty"`
	ProfileCometWorkProfileFieldEditRendererRendererNormalizationGraphql               FbtLogging               `json:"ProfileCometWorkProfileFieldEditRenderer_renderer$normalization.graphql,omitempty"`
	ProfileCometWorkProfileFieldEditRendererReact                                      BladeRunnerClient        `json:"ProfileCometWorkProfileFieldEditRenderer.react,omitempty"`
	ProfileCometWorkProfileFieldEditFormReact                                          CometCompatModalReact    `json:"ProfileCometWorkProfileFieldEditForm.react,omitempty"`
	ProfileCometDetailedProfileFieldRendererRendererNormalizationGraphql               FbtLogging               `json:"ProfileCometDetailedProfileFieldRenderer_renderer$normalization.graphql,omitempty"`
	ProfileCometDetailedProfileFieldRendererReact                                      BladeRunnerClient        `json:"ProfileCometDetailedProfileFieldRenderer.react,omitempty"`
	ProfileCometSecondarySchoolProfileFieldEditRendererRendererNormalizationGraphql    FbtLogging               `json:"ProfileCometSecondarySchoolProfileFieldEditRenderer_renderer$normalization.graphql,omitempty"`
	ProfileCometSecondarySchoolProfileFieldEditRendererReact                           BladeRunnerClient        `json:"ProfileCometSecondarySchoolProfileFieldEditRenderer.react,omitempty"`
	ProfileCometSecondarySchoolProfileFieldEditFormReact                               CometCompatModalReact    `json:"ProfileCometSecondarySchoolProfileFieldEditForm.react,omitempty"`
	ProfileCometCollegeProfileFieldEditRendererRendererNormalizationGraphql            FbtLogging               `json:"ProfileCometCollegeProfileFieldEditRenderer_renderer$normalization.graphql,omitempty"`
	ProfileCometCollegeProfileFieldEditRendererReact                                   BladeRunnerClient        `json:"ProfileCometCollegeProfileFieldEditRenderer.react,omitempty"`
	ProfileCometCollegeProfileFieldEditFormReact                                       CometCompatModalReact    `json:"ProfileCometCollegeProfileFieldEditForm.react,omitempty"`
	PagesCometPageLinkPageNormalizationGraphql                                         FbtLogging               `json:"PagesCometPageLink_page$normalization.graphql,omitempty"`
	PagesCometPageLinkReact                                                            BladeRunnerClient        `json:"PagesCometPageLink.react,omitempty"`
	CometConfirmationDialogImplReact                                                   BladeRunnerClient        `json:"CometConfirmationDialogImpl.react,omitempty"`
	FbtLogging                                                                         FbtLogging               `json:"FbtLogging,omitempty"`
	LynxAsyncCallbackFalcoEvent                                                        BladeRunnerClient        `json:"LynxAsyncCallbackFalcoEvent,omitempty"`
	CometSuspenseFalcoEvent                                                            BladeRunnerClient        `json:"CometSuspenseFalcoEvent,omitempty"`
	BanzaiScubaDEPRECATED                                                              BanzaiScubaDEPRECATED    `json:"BanzaiScuba_DEPRECATED,omitempty"`
	SkywalkerUtils                                                                     FbtLogging               `json:"SkywalkerUtils,omitempty"`
	CometToastReact                                                                    BladeRunnerClient        `json:"CometToast.react,omitempty"`
	CometAlertDialogImplReact                                                          BladeRunnerClient        `json:"CometAlertDialogImpl.react,omitempty"`
	FleetBeaconSubscriptionLauncher                                                    BladeRunnerClient        `json:"FleetBeaconSubscriptionLauncher,omitempty"`
	CometRelayEF                                                                       BladeRunnerClient        `json:"CometRelayEF,omitempty"`
	WebFunnelLogger                                                                    BladeRunnerClient        `json:"WebFunnelLogger,omitempty"`
	ProfileCometAboutExperienceDropdownReact                                           BladeRunnerClient        `json:"ProfileCometAboutExperienceDropdown.react,omitempty"`
	MqttLongPollingRunner                                                              FbtLogging               `json:"MqttLongPollingRunner,omitempty"`
	CometCompatModalReact                                                              CometCompatModalReact    `json:"CometCompatModal.react,omitempty"`
	CometErrorRootReact                                                                CometCompatModalReact    `json:"CometErrorRoot.react,omitempty"`
}
