package raw

type Node struct {
	Tracking                      string          `json:"tracking,omitempty"`
	StyleRenderer                 *Renderer       `json:"style_renderer,omitempty"`
	ID                            string          `json:"id,omitempty"`
	FieldType                     string          `json:"field_type,omitempty"`
	Renderer                      *Renderer       `json:"renderer,omitempty"`
	EditRenderer                  interface{}     `json:"edit_renderer,omitempty"`
	LinkURL                       string          `json:"link_url,omitempty"`
	GroupKey                      string          `json:"group_key,omitempty"`
	Icon                          *Icon           `json:"icon,omitempty"`
	PrivacyScope                  interface{}     `json:"privacy_scope,omitempty"`
	Year                          int64           `json:"year,omitempty"`
	YearOverview                  *YearOverview   `json:"year_overview,omitempty"`
	URL                           string          `json:"url,omitempty"`
	Attachments                   []Attachment    `json:"attachments,omitempty"`
	Name                          string          `json:"name,omitempty"`
	Items                         *Items          `json:"items,omitempty"`
	NullStateMsg                  string          `json:"null_state_msg,omitempty"`
	Typename                      string          `json:"__typename,omitempty"`
	DebugInfo                     interface{}     `json:"debug_info,omitempty"`
	SponsoredData                 interface{}     `json:"sponsored_data,omitempty"`
	EncryptedTracking             string          `json:"encrypted_tracking,omitempty"`
	ViewabilityConfig             []int64         `json:"viewability_config,omitempty"`
	AttachedStory                 *Story          `json:"attached_story,omitempty"`
	CreationTime                  int64           `json:"creation_time,omitempty"`
	BackdatedTime                 interface{}     `json:"backdated_time,omitempty"`
	ClickTrackingLinkshimCb       string          `json:"click_tracking_linkshim_cb,omitempty"`
	EncryptedClickTracking        string          `json:"encrypted_click_tracking,omitempty"`
	AssociatedGroup               interface{}     `json:"associated_group,omitempty"`
	TopReactions                  *TopReactions   `json:"top_reactions,omitempty"`
	OuterHeader                   interface{}     `json:"outer_header,omitempty"`
	Header                        interface{}     `json:"header,omitempty"`
	ContextLayout                 *Story          `json:"context_layout,omitempty"`
	AymtFooter                    interface{}     `json:"aymt_footer,omitempty"`
	Footer                        interface{}     `json:"footer,omitempty"`
	OuterFooter                   interface{}     `json:"outer_footer,omitempty"`
	LegacyFbid                    string          `json:"legacy_fbid,omitempty"`
	Author                        *Author         `json:"author,omitempty"`
	IsAuthorWeakReference         bool            `json:"is_author_weak_reference,omitempty"`
	CreatedTime                   int64           `json:"created_time,omitempty"`
	SpamDisplayMode               string          `json:"spam_display_mode,omitempty"`
	ShouldShowCommentMenu         bool            `json:"should_show_comment_menu,omitempty"`
	IsAuthorBannedByContentOwner  bool            `json:"is_author_banned_by_content_owner,omitempty"`
	EditHistory                   *ReactionCount  `json:"edit_history,omitempty"`
	PageAdminActorInfo            interface{}     `json:"page_admin_actor_info,omitempty"`
	ParentFeedback                *Feedback       `json:"parent_feedback,omitempty"`
	PrivateReplyContext           interface{}     `json:"private_reply_context,omitempty"`
	PreferredBody                 *Renderer       `json:"preferred_body,omitempty"`
	TranslationAvailableForViewer bool            `json:"translation_available_for_viewer,omitempty"`
	BodyRenderer                  *Renderer       `json:"body_renderer,omitempty"`
	TimestampInVideo              interface{}     `json:"timestamp_in_video,omitempty"`
	WrittenWhileVideoWasLive      bool            `json:"written_while_video_was_live,omitempty"`
	GroupCommentInfo              interface{}     `json:"group_comment_info,omitempty"`
	HasConstituentBadge           bool            `json:"has_constituent_badge,omitempty"`
	CanSeeConstituentBadgeUpsell  bool            `json:"can_see_constituent_badge_upsell,omitempty"`
	LegacyToken                   string          `json:"legacy_token,omitempty"`
	IdentityBadgesWeb             []interface{}   `json:"identity_badges_web,omitempty"`
	CanShowMultipleIdentityBadges bool            `json:"can_show_multiple_identity_badges,omitempty"`
	CanViewerDisablePreview       bool            `json:"can_viewer_disable_preview,omitempty"`
	IsHiddenByContentOwner        interface{}     `json:"is_hidden_by_content_owner,omitempty"`
	InlineSurveyConfig            interface{}     `json:"inline_survey_config,omitempty"`
	Body                          *Body           `json:"body,omitempty"`
	IsMarkdownEnabled             bool            `json:"is_markdown_enabled,omitempty"`
	ReplyParentComment            interface{}     `json:"reply_parent_comment,omitempty"`
	FlatThreadingDepth            int64           `json:"flat_threading_depth,omitempty"`
	Key                           int64           `json:"key,omitempty"`
	ReactionType                  string          `json:"reaction_type,omitempty"`
	LocalizedName                 string          `json:"localized_name,omitempty,omitempty"`
	SectionType                   string          `json:"section_type,omitempty"`
	Image                         *Image          `json:"image,omitempty"`
	ActionsRenderer               *Renderer       `json:"actions_renderer,omitempty"`
	FriendshipStatus              string          `json:"friendship_status,omitempty"`
	ProfileURL                    string          `json:"profile_url,omitempty"`
	DisplayableCount              int             `json:"displayable_count,omitempty"`
	FirstCardToShow               interface{}     `json:"first_card_to_show,omitempty"`
	Title                         *Title          `json:"title,omitempty"`
	CometSections                 *CometSections  `json:"comet_sections,omitempty"`
	Feedback                      *Feedback       `json:"feedback,omitempty"`
	AllCollections                *AllCollections `json:"all_collections,omitempty"`
	CategoryType                  string          `json:"category_type,omitempty"`
	ExternalURL                   string          `json:"external_url,omitempty,omitempty"`
	Node                          *Node           `json:"node,omitempty"`
	IsAuthorOriginalPoster        bool            `json:"is_author_original_poster,omitempty"`
	IsViewerCommentPoster         bool            `json:"is_viewer_comment_poster,omitempty"`
}
